### ISSUE TITLE
porkbun v0.5.0 has `pp options` not present in Git

### ISSUE THREAD

**Issue by davispuh** [danielb2/porkbun-ruby#2]
porkbun v0.5.0 has `pp options` not present in Git. Look at 

```diff
diff --git a/porkbun.rb.1 b/porkbun.rb
index 6939f55..bf3b414 100644
--- a/porkbun.rb
+++ b/porkbun.rb
@@ -7,6 +7,7 @@ module Porkbun
   class Error < StandardError; end

   def self.porkbun(path, options = {})
+    pp options
     if ENV.fetch('PORKBUN_API_KEY', nil).nil? || ENV.fetch('PORKBUN_SECRET_API_KEY', nil).nil?
       abort 'PORKBUN_API_KEY and PORKBUN_SECRET_API_KEY must be set'
     end
```

Could you update gem version to match with Git's repo?

**Comment by danielb2** [comment]
Yes. I'll fix in a few hours. I'm afk. Thanks for reporting

**Comment by danielb2** [comment]
released v0.5.1

**Comment by davispuh** [comment]
Awesome! Thanks for quick response and for maintaining this gem. I just released [ConfigLMM](/ConfigLMM/ConfigLMM) take a look! :)

Using it I deploy my domains with simple config
```yaml
Porkbun:
    Type: PorkbunDNS
    DNS:
        example.org:
            '@': A=@me # `@me` means use current hosts external IP
        example.com:
            '@': ALIAS=example.org
```
